apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Helm Module</title>
    <style>
    html { color-scheme:light dark; }
    body { width: 35em; margin: 0 auto; font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Helm Module</h1>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: {{ include "mychart.name" . }}-configmap
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
